### ISSUE TITLE
TODO LIST

### ISSUE THREAD

**Issue by ssssooyoung** [ssssooyoung/podcast-parser#1]
- [ ] 현재 재생중인 항목 리스트에 표시
- [ ] 찾은 팟캐스트 북마크 기능
- [ ] 플레이어 영역 스타일링
- [ ] 일렉트론으로 감싸기

**Comment by ssssooyoung** [comment]
- [ ] 방송 리스트 필터링 (일단은 텍스트 검색 스타일로)

**Comment by ssssooyoung** [comment]
북마크 리스트 파일로 저장/불러오기
